/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY codergen. EDIT WITH CARE.
 */
package com.android.tools.rpclib.schema;

import com.intellij.ui.SimpleColoredComponent;
import com.intellij.ui.SimpleTextAttributes;
import org.jetbrains.annotations.NotNull;

import com.android.tools.rpclib.binary.BinaryClass;
import com.android.tools.rpclib.binary.BinaryID;
import com.android.tools.rpclib.binary.BinaryObject;
import com.android.tools.rpclib.binary.Decoder;
import com.android.tools.rpclib.binary.Encoder;
import com.android.tools.rpclib.binary.Namespace;

import java.io.IOException;

public final class Slice extends Type {
    @NotNull
    @Override
    public String getName() {
        return "slice<" + mValueType.getName() + ">";
    }

    @Override
    public void encodeValue(@NotNull Encoder e, Object value) throws IOException {
        assert(value instanceof Object[]);
        Object[] array = (Object[])value;
        e.uint32(array.length);
        for(Object v : array) {
            mValueType.encodeValue(e, v);
        }
    }

    @Override
    public Object decodeValue(@NotNull Decoder d) throws IOException {
        int size = (int)d.uint32();
        Object[] array = new Object[size];
        for(int i =0; i < size; i++) {
            array[i] = mValueType.decodeValue(d);
        }
        return array;
    }

    @Override
    public void render(@NotNull Object value, @NotNull SimpleColoredComponent component, SimpleTextAttributes defaultAttributes) {
        Render.array(value, mValueType, component, defaultAttributes);
    }

    //<<<Start:Java.ClassBody:1>>>
    private String mAlias;
    private Type mValueType;

    // Constructs a default-initialized {@link Slice}.
    public Slice() {}


    public String getAlias() {
        return mAlias;
    }

    public Slice setAlias(String v) {
        mAlias = v;
        return this;
    }

    public Type getValueType() {
        return mValueType;
    }

    public Slice setValueType(Type v) {
        mValueType = v;
        return this;
    }

    @Override @NotNull
    public BinaryClass klass() { return Klass.INSTANCE; }

    private static final byte[] IDBytes = {59, 117, -18, 89, 24, 26, 77, 116, 80, -14, 80, 127, -7, 79, 121, -103, 56, 88, -106, -46, };
    public static final BinaryID ID = new BinaryID(IDBytes);

    static {
        Namespace.register(ID, Klass.INSTANCE);
    }
    public static void register() {}
    //<<<End:Java.ClassBody:1>>>
    public enum Klass implements BinaryClass {
        //<<<Start:Java.KlassBody:2>>>
        INSTANCE;

        @Override @NotNull
        public BinaryID id() { return ID; }

        @Override @NotNull
        public BinaryObject create() { return new Slice(); }

        @Override
        public void encode(@NotNull Encoder e, BinaryObject obj) throws IOException {
            Slice o = (Slice)obj;
            e.string(o.mAlias);
            e.object(o.mValueType.unwrap());
        }

        @Override
        public void decode(@NotNull Decoder d, BinaryObject obj) throws IOException {
            Slice o = (Slice)obj;
            o.mAlias = d.string();
            o.mValueType = Type.wrap(d.object());
        }
        //<<<End:Java.KlassBody:2>>>
    }
}
