/**
 * DO NOT EDIT
 * This file was generated by xjc from repo-sites-common-1.xsd. Any changes will be lost upon recompilation of the schema.
 * See the schema file for instructions on running xjc.
 * 
 */
package com.android.repository.impl.meta;
